### PR TITLE
Added support for ASGSADMIN_ID.

### LINKED ISSUE #1122: configure `catalog.html` for WWW directory listing not facilitated by THREDDS
Make `catalog.html` the default in whatever is done so existing definitions (core and locally defined) still use `catalog.html`. This will impact `opendap_post2.sh` mainly in the construction of the email notification message.

### LINKED ISSUE #1124: provide overide to `ASGSADMIN` being used in `opendap_post2.sh` for unique identifier in email subject
- [x] `ASGSADMIN_UUID` should replace `ASGSADMIN` in email subject lines when defined.
- [x] #1122

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 1124: Refining support for controlling the length and information presented in the email subjects sent via opendap_post2.sh.

Resolves #1124.
Resolves #1122.
Supercedes #1118 (PR).

Updated info at:

https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide
https://github.com/StormSurgeLive/asgs/wiki/ASGS-Cheat-Sheet
https://raw.githubusercontent.com/StormSurgeLive/asgs/561ce157c97a2b1aab08fe576a700d884892157a/ssh-servers/tacc_tds3.sh

### CODE REVIEW

**Comment by wwlwpd** [comment]
This PR supercede PR, #1118.

**Comment by wwlwpd** [comment]
Testing as part of the ongoing readiness exercise.

**Review by jasonfleming — DISMISSED** [review]
This looks great @wwlwpd the only thing left is documentation (as you've noted elsewhere).

**Comment by wwlwpd** [comment]
Updated info at:

https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide
https://github.com/StormSurgeLive/asgs/wiki/ASGS-Cheat-Sheet
https://raw.githubusercontent.com/StormSurgeLive/asgs/561ce157c97a2b1aab08fe576a700d884892157a/ssh-servers/tacc_tds3.sh

**Pull request closed without merging**
