### PR TITLE
ASGS backup/restore support

### PR DESCRIPTION
**Pull request by wwlwpd**
Things to do to make this "complete":

- [x] add support for specifying tgz file, including supporting ~~`ssh://`~~ (looks for `host:filePath` like `rsync`)
- [x] add metadata, particularly tracking: a) the commit SHA of ASGS, b) the _machine_ name, c) the absolute path of the ASGS installation, d) MD5 of the file containing list of MD5 checksums (cross check)
- [x] roll metadata and MD5 file listing into the tgz itself
- [x] add some basic MD5 hash checksum verification to ensure everything
- [x] cross check MD5 of MD5 listing with what's in the meta data and vice-versa
- [x] in `backup`, fatal if destination file exists locally
- [x] in `backup`, fatal if destination file exists remotely (`HOST:/path/to/file`)
- [x] in `backup`, fatal if `.tgz` not present at the end of the destination file
- [x] in `backup`, fatal if destination file is in ASGS directory being backed up

### CODE REVIEW

**Comment by wwlwpd** [comment]
I need to add some md5 checksum checking, but I think it's all essentially here. I can do a demo for you, @jasonfleming, so I can get some valuable feedback. It doesn't yet support sending or receiving files involving a remote location, but easily can add that so it supports any remote servers tracked in `.ssh/config`.

**Comment by wwlwpd** [comment]
- [ ] add support for specifying tgz file, including supporting `ssh://`
- [ ] add metadata, particularly tracking: a) the commit SHA of ASGS, b) the _machine_ name, c) the absolute path of the ASGS installation, d) MD5 of the file containing list of MD5 checksums (cross check)
- [ ] roll metadata and MD5 file listing into the tgz itself
- [ ] add some basic MD5 hash checksum verification to ensure everything
- [ ] cross check MD5 of MD5 listing with what's in the meta data and vice-versa

**Comment by wwlwpd** [comment]
This may require a call, but here is the breakdown. Please look for errors, missing _requirements_, confusing things, try to break it, etc.

Testing instructions:

1. (optional) git clone asgs
2. (optional) build a new asgs
3. (outside of `./asgsh`), run `bin/backup /path/to/my-backup.tgz`
4. (outside of `./asgsh`), run `bin/DELETE` (for purpose of cleaning out repo)
5. (outside of `./asgsh`), run `bin/restore /path/to/my-backup.tgz`

Testing variations:

1. outside of `./asgsh` (above)
2. inside of `./asgsh` (available through `PATH`)
3. `/path/to/my-backup.tgz` not specified (default is, `$HOME/ASGS-SAVE-${PWD}.tgz`)
4. remote file path of the form, `HOST:~/my-remote-bkp.tgz`

Error conditions:

Fatal errors include:

- git commit SHA doesn't match
- absolute `pwd` is not the same
- file containing MD5 of files doesn't match its own MD5

Warning errors include:

- machine name (from `bin/guess platform`) doesn't match

**Comment by wwlwpd** [comment]
I'll be testing on different HPC platforms.

**Comment by jasonfleming** [comment]
I am now building this on Frontera and debian.local

**Comment by wwlwpd** [comment]
Added:

* requires `.tgz` (fatal if not part of `backup` destination name
* requires file not be in `pwd` (i.e., the directory being backed up)
* fatal if destination file exists locally or remotely

**Comment by wwlwpd** [comment]
@jasonfleming - mind if I merge this? It's 100% new, except for some updates to `help`. We'll find things we want to change or fix as we use it.

**Review by jasonfleming — APPROVED** [review]
Great new features!

**Comment by jasonfleming** [comment]
Yes please go for it.

**Comment by wwlwpd** [comment]
> Yes please go for it.

Thank you!

**Pull request merged**
