### PR TITLE
ADCIRC build support mega-update

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 1386:

Related to #1386

Testing list:

**Frontera**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**Lonestar6**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**Stampede3**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**Mike III**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**QBC**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**QBD**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**Ubuntu (gfortran)**
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

**Ubuntu (OneAPI)** (saving this one for last since most of the work was done here)
- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2

### CODE REVIEW

**Comment by wwlwpd** [comment]
building this to make sure it didn't break anything

**Comment by wwlwpd** [comment]
no problems detected

**Review by jasonfleming — COMMENTED** [review]
This looks good, and well targeted in the scripting. I have not tried the updated patch sets yet, but will do so now.

**Comment by jasonfleming** [comment]
@wwlwpd If I build and install ASGS with intel, can I build `adcirc` with intel-oneapi? Or do they have to match?

**Comment by wwlwpd** [comment]
> @wwlwpd If I build and install ASGS with intel, can I build `adcirc` with intel-oneapi? Or do they have to match?

It'll have to match. But this is required on Stampede3, so you can try it there if you've built before.

**Comment by wwlwpd** [comment]
@jasonfleming During the testing above, I discovered that I had to remove `-FI` for all supported machines for Intel - so it as definitely something new that was introduced with v56 via the `src/netcdf_error.F90` file. I ended up removing all instances of `-FI` in the whole file. I need to test Rostam,  but not before this gets merged. Once I finish testing Ubuntu gfortran and Ubuntu with Intel OneAPI, this will be ready for a squash and merge. I am hopeful that will work out just fine, so will now make it ready for review.

**Comment by wwlwpd** [comment]
There are some other versions in the list I want to remove, but that can also wait.

**Comment by wwlwpd** [comment]
WWe handle it, but was able to get a clear enough picture of what's going on to submit this bug upstream to ADCIRC regarding their make build system, https://github.com/adcirc/adcirc/issues/408

**Comment by wwlwpd** [comment]
Note as reference for an issue I will create, but the _ADCIRC Live_ WSL2 VM that is build and distributed currently has the `MACHINENAME=wsl-ubuntu` - and all the build patches for ADCIRC go off of `MACHINENAME=debian` - so I will have to address this after this gets merged and I update the `adcirclive branch` and roll updated VMs.

**Comment by wwlwpd** [comment]
I rebased this with `master` after merging #1386.

**Pull request merged**
