### PR TITLE
Adding support for Bama's CHPC Cluster.

### LINKED ISSUE #1202: add UAHPC to list of officially supported platforms
Modules environment is needed to load in `ifort` and `mpif90` (commonly needed on public/gov't systems):

`$HOME/.modules`
```
module load compilers/intel/2020
module load mpi/openmpi/intel/1.8.4
```

Initial questions:

- [x] the path of the standard "work" directory (where we can keep the main ASGS directory)
- - `/twater/$USER`
- [x] the path of the "scratch" directory - where the runs actually take place
- - `/twater/$USER`
- [x] should the default compiler be `gfortran` or Intel
- - Intel
- [x] what OpenMPI+compiler options are available (via `modules` tool)
- see above for the entries to make into `$HOME/.bashrc` (`~/.modules` seems to not be read on login)
- [x] what is the output of `hostname --fqdn`
- `uahpc.ua.edu` _full_ name
- `uahc` as _short_ name

### PR DESCRIPTION
**Pull request by wwlwpd**
@jasonfleming I need to get Javier attached to this also so we can test. 

...

Issue 1202: This commit will make CHPC a default option when running the ./init-asgs.sh installation wizard for ASGS.

Resolves #1202.

### CODE REVIEW

**Comment by wwlwpd** [comment]
image

**Comment by jasonfleming** [comment]
excellent

**Comment by wwlwpd** [comment]
Works, tested .. checkout the new README feature!

image

**Review by jasonfleming — APPROVED** [review]
Looks great, this dropped right in! Looking forward to working with this in the future.

**Pull request merged**
