### PR TITLE
extended default output end time to 9999.0 days

### LINKED ISSUE #720: extend adcirc output time range past 365 days
The `control_file_gen.pl` script hardcodes the time range of time series output to start at 0.0 days (i.e., at cold start) until 365.0 days after cold start. This is an issue for long running simulations because the time series output will stop after one year of simulation time. The short term workaround is to extend the hard coded ending value to 9999.0 days. A marginally more useful long term fix would be to make the start and end time of output for each output file type configurable with reasonable default values.

### PR DESCRIPTION
**Pull request by jasonfleming**
Resolves #720

### CODE REVIEW

**Review by wwlwpd — DISMISSED** [review]
looks good to me

**Comment by jasonfleming** [comment]
@wwlwpd I am testing this now

**Comment by jasonfleming** [comment]
@wwlwpd This is a really minor bug fix, and looks good to me now, my testing was successful. I resolved the merge conflicts right on the github site, and did not realize it merged master into my issue branch. Hope that's ok. Please have a look. :-)

**Comment by wwlwpd** [comment]
I merged latest master and squashed the feature branch

**Review by wwlwpd — APPROVED** [review]
looks good to me

**Pull request merged**
