### PR TITLE
invasive correction for mail integration

### PR DESCRIPTION
**Pull request by wwlwpd**
* moved $SCRIPTDIR/asgs-sendmail.pl -> $SCRIPTDIR/bin/asgs-sendmail (so it's in `asgsh`'s `$PATH`)
* updated all places in repo that used it, except one place that was attaching files
* NOTE: some places were still using the system `mail` utility, which was unexpected (my fault)

### CODE REVIEW

**Comment by wwlwpd** [comment]
@jasonfleming when you review this, make sure `asgs-sendmail` usage fits the following criteria:

* assume it's available via `$PATH`
* email body should be getting redirected INTO the script
* flags `--subject` and `--to` should be the only ones used
* shell variables being used for `--subject` and `--to` should be contained in DOUBLE qoutes

Examples,

* `cat somefile.txt | asgs-sendmail --subject "some subject $OTHERSUBJECTINFO" --to "$SOME_EMAIL_LIST" 2>> $SYSLOG`
* `asgs-sendmail --subject "some subject $OTHERSUBJECTINFO" --to "$SOME_EMAIL_LIST" < somefile.txt 2>> $SYSLOG`

Let me know if something doesn't look right. `asgs-sendmail` is not used where attachments are added (only one place I think).

**Review by jasonfleming — CHANGES_REQUESTED** [review]
It may not matter but line 401 in `opendap_post.sh` does not have `""` around `$OPENDAPNOTIFY` for the `--to` cmd line arg

Lines 421, 535, 605, and 638 in `opendap_post2.sh` do not enclose `$OPENDAPNOTIFY` in `""` for the `--to` cmd line arg

line 248 in `scp_only.sh` does not enclose `$OPENDAPNOTIFY` in `""` for the `--to` cmd line arg

Is it possible to check `$?` after `asgs-sendmail` is executed and issue a `warn()` message if it does not come back with `0`?

**Comment by wwlwpd** [comment]
great thank you, I can do all that - I want to delete `opendap_post.sh` or rename `opendap_post2.sh` to that name..thoughts?

**Comment by jasonfleming** [comment]
Delete/rename: That is fine, but we have a good system now where the script name can be arbitrary b/c it is a shell variable rather than being hard coded. 

I think you mentioned at some point wanting to get rid of the term "opendap" b/c it is not actually relevant to the action performed by this script. I agree. Can we rename this script `upload.sh` and make that name the default?

**Comment by wwlwpd** [comment]
> Delete/rename: That is fine, but we have a good system now where the script name can be arbitrary b/c it is a shell variable rather than being hard coded.
> 
> I think you mentioned at some point wanting to get rid of the term "opendap" b/c it is not actually relevant to the action performed by this script. I agree. Can we rename this script `upload.sh` and make that name the default?

I am not against that, but despite my proactive tone at the start I think this would just confuse things :) - we can do it some other time, though.

**Comment by wwlwpd** [comment]
Changes request were made, this is ready for your review. I think you have to "resolve conversation" since you requested the change in the review.

**Comment by wwlwpd** [comment]
but do take some time with this one, not trying to add pressure (none that's not already there :))

**Review by jasonfleming — APPROVED** [review]

**Comment by jasonfleming** [comment]
Great to have a simpler script to work with. Name the script as you see fit, I am open to anything. Please go ahead and merge. :-)

**Pull request merged**
