### PR TITLE
Made prompt more configurable and added more useful prompt.

### LINKED ISSUE #1089: Adding customizable prompt via `$PS1`
Prompt can be customized via normal means, by setting and exporting `PS1` in the environment.

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue-1089: Added more useful prompt, updates git branch automatically; added colors and created a separate script just for this (etc/PS1.sh).

'info' and 'warning' alerts now are colored, where implemented.

To update, just run,

  ./update-asgs --update-shell

Resolves #1089.

### CODE REVIEW

**Comment by wwlwpd** [comment]
Example,

image

**Comment by jasonfleming** [comment]
My prompt did not end up looking like yours, I think there may be a file missing from the commit (`PS1.sh`): 
issue-1089-missing-PS1 sh

**Comment by wwlwpd** [comment]
Sorry about that, fix up adds it. But it's good to see the colors show up for the other stuff (`info`, etc).

**Comment by wwlwpd** [comment]
forced pushed new commit

**Pull request closed without merging**
