### PR TITLE
Added "fetch" command.

### LINKED ISSUE #737: add `fetch` command to get commonly used repos
Getting and updating asgs-configs from `asgsh` should be a command away (all underneath are `git` commands),

* `fetch configs`            -> wrapper around `git clone` of `asgs-configs` (run once)
* `fetch docs`                -> wrapper around `git clone` of `asgs.wiki`
* `fetch storm-archive`  -> ... `storm-archve`
* allow custom repo aliases to be configured
* all repos go into `$SCRIPTDIR/git`

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 737: 'fetch' command allows for the easy "getting" (via git checkout
or some other means) of eternal ASGS resources.

Supports:

  asgs-configs
  asgs.wiki
  cera-asgs
  storm-archive
  adcirc-testsuite

Resolves #737.

### CODE REVIEW

**Comment by wwlwpd** [comment]
FWIW, this will help speed up setting up runs very much since we've split out the configs from the main repo. In addition to this, it makes to wiki, available as a separate repo, `asgs.wiki`, available easily - both for reading and for update/editing.

**Review by jasonfleming — DISMISSED** [review]
Hey @wwlwpd this looks great. Is there a way we can make this into a dynamic and Operator-configurable list of repos (like what you did with the `platforms` directory)? Or maybe have a standard list that an individual Operator can add things to? Also, can we call the subdirectory where they are cloned `resources` or `repos` rather than `git` to better capture the essence of what is stored there and why? Also, in terms of the choices available in the standard list, I would probably add the `asgs_operators` repo and maybe remove the `cera-asgs` repo. Finally, could there be a  companion to the `fetch` command that would do a `git fetch --all && git pull` on the repo(s) that have already been `git clone`d?

**Comment by wwlwpd** [comment]
I forgot about asgs_operators...and yes, I figured cera would be slightly controversial, but maybe we can come up with a way to specify additional repo/alias in `~/.asgs_profile`. Thanks for the feedback!

**Comment by wwlwpd** [comment]
Oh, as far as adding the update, I need to think about it more; I figured that after that someone could just drop down into the directory and do `git`-fu directly..no reason to have a wrapper around it for sticky situations.

So maybe add them to the `goto` command? E.g.,

```
asgs> fetch configs
asgs> goto configs
asgs> git ...
```

What do you think there? We might need to discuss directly since it's kind of a nuanced topic.

**Comment by jasonfleming** [comment]
I agree there are some finer points to consider here. Perhaps merge it the way it is, get some experience working with it, and then refine it in the future based on that experience?

**Comment by wwlwpd** [comment]
I can live with that 😄 !

**Comment by notstarboard** [comment]
This is super cool! As a new user I definitely didn't know where to go for documentation, so being able to just fun "fetch docs" and then explore around is awesome.

Two pieces of feedback:
1. fetch will tell you "cloning into [directory]..." when it's running, but it would be clearer if that [directory] was the full path, or at least /asgs/git/[directory]. I was initially confused when it said "cloning into asgs.wiki" but the "asgs.wiki" directory didn't seem to exist. 
2. Have you considered how users will find out that this function exists? For example, is this something you might consider adding to the "Quick Start" list when you start up ASGS? It would be a shame for it to be a sort of buried functionality, especially when downloading the documentation could be really useful for beginners.

It seems to work as intended, though, so I'll approve! If you'd like to address either of these, though, I'd happily look again!

**Review by notstarboard — DISMISSED** [review]

**Comment by wwlwpd** [comment]
> This is super cool! As a new user I definitely didn't know where to go for documentation, for example, so being able to just run "fetch docs" and then explore around is awesome.
> 
> Two pieces of feedback:
> 
>     1. fetch will tell you "cloning into [directory]..." when it's running, but it would be clearer if that [directory] was the full path, or at least "asgs/git/[directory]". I was initially confused when it said "cloning into asgs.wiki" but the "asgs.wiki" directory didn't seem to exist.
> 
>     2. Have you considered how users will find out that this function exists? For example, is this something you might consider adding to the "Quick Start" list when you start up ASGS? It would be a shame for it to be a sort of buried functionality, especially when downloading the documentation could be really useful for beginners.
> 
> 
> It seems to work as intended, though, so I'll approve! If you'd like to address either of these, though, I'd happily look again!

Good stuff, I'll take a look at making some of this more clear before the merge. I also agree, this should be in the quick start/cheat sheet!

**Comment by wwlwpd** [comment]
@notstarboard I added some more detail during the checkout phase, it was from `git` so I had to be more explicit with the path I was giving to `git`. E.g.,

```
asgs (default-asgs)> fetch configs
Cloning into '/ddnA/qb2work/USER/asgs-prod/git/asgs-configs'...
remote: Enumerating objects: 916, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 916 (delta 36), reused 26 (delta 16), pack-reused 869
Receiving objects: 100% (916/916), 410.96 KiB | 0 bytes/s, done.
Resolving deltas: 100% (794/794), done.

```

**Review by notstarboard — APPROVED** [review]
Changes look good!

**Review by notstarboard — DISMISSED** [review]

**Comment by wwlwpd** [comment]
Added to, https://github.com/StormSurgeLive/asgs/wiki/ASGS-Cheat-Sheet

I need to update the `help` output...

**Comment by wwlwpd** [comment]
Okay, I added the help menu entry.

**Review by notstarboard — APPROVED** [review]
Nice 👍

**Review by jasonfleming — APPROVED** [review]
This is great, @wwlwpd thank you!

**Pull request merged**
