### PR TITLE
Backporting some fixes and enhancements found in the adcirclive branch.

### LINKED ISSUE #1300: backport adcirclive updates to core files
after the usergroup meeting and bootcamp, some core files were improved:

* `/init-asgs.sh`
* `cloud/general/t/verify-adcirc.sh` (fixed)
* `cloud/general/asgs-brew.pl` (added working `-A` to `asgsh`)

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 1300:

- added "-A 'run any command'" to asgsh (which is generated by asgs-brew.pl)
- fix an issue that was disallowing "verify adcirc" to run correctly
- minor changes in init-asgs.sh - someone overlap with #1271

Resolves #1300.

### CODE REVIEW

**Review by jasonfleming — COMMENTED** [review]
This looks good but I am not familiar enough with this functionality to understand the changes. Should I test this myself? Also, I liked the X-Wing ... :-)

**Comment by wwlwpd** [comment]
Great feedback, I will add it back! The functional changes include:

* adding `-A` to the generated `asgsh` that allows for the running of an arbitrary ASGS command outside of the shell
* `init-asgs.sh` is also aware of the `adcirclive` directory and tools, which will not be maintained in `master` but will be used in ADCIRC Live nonetheless
* `verify adcirc` was not working I discovered, so that is a bug fix

**Comment by wwlwpd** [comment]
I updated the repo to add the x-wing back, gave me another opportunity to also update the asgsh splash screen.

**Review by jasonfleming — APPROVED** [review]
This looks good. Please merge. :-)

**Pull request merged**
