### PR TITLE
updates to hook script architecture to support posting of hindcasts and nowcasts to opendap

### LINKED ISSUE #114: nowcast post processing
Add a post processing hook for nowcasts that allow them to be posted to opendap or otherwise analyzed.

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #114

### CODE REVIEW

**Comment by jasonfleming** [comment]
I am converting the hook script loops to the following format: 
```
for i in "${arr[@]}" ; do
   echo "$i" # or do whatever with individual element of the array
done
```

**Comment by jasonfleming** [comment]
resolves #263

**Review by wwlwpd — APPROVED** [review]

**Comment by wwlwpd** [comment]
Manually squashed and merged to `master` via 2c3502640af539ebc3a7e7139b007e1e7b2cedf2

**Comment by wwlwpd** [comment]
resolved via db3dffc7432e5d5deff55f5d2dd5fe358ce7501c, outside of this PR

**Pull request closed without merging**
