### PR TITLE
Updated ADCIRC patches to support mpiifort on supported machines where needed.

### LINKED ISSUE #1140: Update ADCIRC patches to reflect `mpiifort` for some institutionally supported machines
- [x] ADCIRC patches
- [ ] document expected contents of `~/.modules` on rostam

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 1140:

Resolves #1140.

### CODE REVIEW

**Comment by wwlwpd** [comment]
Document contents of `~/.modules` needed for rostam (access to `mpiifort`)

**Comment by jasonfleming** [comment]
I am reviewing this now. Where will the documentation of the `~/.modules` be stored? Do I need that before I can test on rostam?

**Comment by jasonfleming** [comment]
I'm testing all the adcirc builds supported in `master` on my local debian platform with the following bash one-liner (in the asgsh environment):
```bash
for adcirc in $(seq 1 12); do buildnum=$(printf "%03d" $adcirc) ; build adcirc <<BUILDCMDS > adcirc-build-$buildnum.log 2>&1
$adcirc



BUILDCMDS
done
```
Once that finishes, I will try it with the `issue-1149` branch. Then I'll try it on some of the production platforms. Not sure where is the best place to tally the results.

**Comment by jasonfleming** [comment]
Results for the `master` branch are as follows:
```
$ grep 'S U C C E S S !' *.log
adcirc-build-001.log:                        S U C C E S S !             
adcirc-build-003.log:                        S U C C E S S !             
adcirc-build-004.log:                        S U C C E S S !             
adcirc-build-008.log:                        S U C C E S S !             
adcirc-build-009.log:                        S U C C E S S !             
adcirc-build-010.log:                        S U C C E S S !    
```
for the `issue-1140` branch, I get the following results (nothing broken, plus the adcirc selection 11 now works):
```
$ grep 'S U C C E S S !' *.log
adcirc-build-001.log:                        S U C C E S S !             
adcirc-build-003.log:                        S U C C E S S !             
adcirc-build-004.log:                        S U C C E S S !             
adcirc-build-008.log:                        S U C C E S S !             
adcirc-build-009.log:                        S U C C E S S !             
adcirc-build-010.log:                        S U C C E S S !             
adcirc-build-011.log:                        S U C C E S S !            
```

**Comment by wwlwpd** [comment]
Great testing, will merge based on your results and my own. I will need to figure out where best to document the module `load` required for rostam. It actually was in a period of flux a while back, but seems like this configuration could remain stable for a while.

**Pull request closed without merging**
