### PR TITLE
Integrated generation of wind10m layer into workflow to eliminate need for separate scenario

### LINKED ISSUE #1251: Enable inline production of Wind10m layer rather than producing it as a separate scenario
We originally implemented the production of the Wind10m layer as a separate forecast scenario as a short term workaround. However, over time, this layer has grown in importance (including for nowcasts) and its implementation as a separate forecast scenario that must be manually configured is suboptimal for many reasons. As a result, some refactoring of `asgs_main.sh` and the queue script template should be performed to enable the production of this layer by default. The Operator will have the option of turning off the Wind10m layer if that is preferred.

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #1251

### CODE REVIEW

**Comment by jasonfleming** [comment]
Test plan:

- createWind10mLayer: `yes|no`
- SCENARIO: `*Wind10m|not` 
- nodal_attribute_activate: `empty|list`
- NAFILE: `null|populated`

**Comment by jasonfleming** [comment]
In order to accommodate backward compatibility requirements for pre-existing ASGS config files, I developed 32 test cases for this using many different combinations of specifications, both old and new, and created a meta--automation system to run them. Worked out really well. All of the 32 tests use GFS. Will run 2 hindcast test cases with GAHM also before marking this as ready for review.

**Comment by jasonfleming** [comment]
resolves #1258

**Review by wwlwpd — APPROVED** [review]
wow, big change! Looks great, thank you!

**Pull request merged**
