### PR TITLE
Added checks for data file type for grib2 on forecast

### LINKED ISSUE #913: additional fixes for older bash file checks for grib2
The `file` checks for grib2 files are just a smoke test, helpful but not critical. The additional allowance for the test to come back as "data" are really only relevant to older platforms. Newer versions of `file` will report the file type as `grib2` as expected. After pulling the previous set of fixes, additional instances of this issue were discovered.

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #913

### CODE REVIEW

**Review by wwlwpd — CHANGES_REQUESTED** [review]
The line `resolves #913` needs to go in the git commit before you push it up to GitHub if you want merging it to automatically close Issue 913 (for example).

The change request here is to update the git commit,

1. `git commit --amend`
2. edit commit message, save
3. `git push -f origin issue-913 # "force" push to update the  branch & PR`

**Comment by jasonfleming** [comment]
Ok I thought the "resolves #913" was supposed to go in the PR comment, will amend the most recent commit

**Comment by jasonfleming** [comment]
nm I understand the need for the "resolves" in the commit message ... the commit will be cherry picked back to master so the PR message will not be used :-)

**Review by wwlwpd — APPROVED** [review]
looks good to me, merging

**Pull request merged**
