### PR TITLE
Adding system, extending platform support.

### LINKED ISSUE #790: port ASGS to Penguin POD

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 790: Creating a more extensible "system" for adding
new platforms. System also makes it easier for sites to maintain
their own set of supported platforms outside of this repo.

As a test, support for a Penguin Computing system was added.

Resolves #790.

### CODE REVIEW

**Comment by wwlwpd** [comment]
@jasonfleming just a note, looks like builds are going as expected. Existing hardcoded platform support is getting picked up during install, start of `asgsh`, and the start/running of `asgs_main.sh`.

**Review by jasonfleming — APPROVED** [review]
Sorry for the delay. Beautiful work, well executed. I am looking forward to using this new capability.

**Comment by wwlwpd** [comment]
Very good, thank you. I need to do some documentation to round this out. After I update `platforms/README`, I'll give it a push. Note, this adds some convenience options to `./init-asgs.sh` so after the merge I'll probably revisit the ASGSH cheatsheet

**Comment by wwlwpd** [comment]
I just added `./platforms/README` - so going with previous approval.

**Pull request merged**
