### PR TITLE
Cleaning up anything relying on RMQMessaging_Enable - first pass.

### PR DESCRIPTION
**Pull request by wwlwpd**

### CODE REVIEW

**Comment by wwlwpd** [comment]
There are a couple of key things that I addressed in this PR

1. One had to do with a cat command that was getting $CONFIG content to send to RMQ in the start up, If $CONFIG is hosed some how (e.g., file doesn't exist) on start up, the cat command will hang - low probability but possible

2. The signal traps in monitoring/logging.sh were calling RMQ functions before the RMQ functions were defined in the same file; this is bash so best to only call things after they've been clearly defined

Those both could have caused "weird" issues. I also added some checks for RMQ scripts that were assumed to exist and quoted anything going into the actual Python based client.

**Comment by wwlwpd** [comment]
Any concerns with this PR @BrianOBlanton ?

**Comment by wwlwpd** [comment]
Once this gets through, I'll follow up with a PR for #507.

**Review by jasonfleming — APPROVED** [review]
These are all great. We have our work cut out for us, in terms of getting things cleaner and tighter throughout ASGS. This is a nice step in that direction.

**Pull request merged**
