### PR TITLE
Adding `postExcludeFiles` supports

### LINKED ISSUE #905: add `postExcludeFiles` to complement `postAdditionalFiles` (was customized output file list for Opendap)
ASGS produces a list of default files as output and posts those files to an Opendap server. 
When working on test projects that do not require the full set of output files, would it be possible to submit a customized list of output files to be generated by ADCIRC and/or posted to the OpenDap?

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 905: adding a list of files in the configuration file
via 'postExcludeFiles" will prevent them from being processed
and uploaded via output/opendap_post2.sh.

Resolves #905.

### CODE REVIEW

**Comment by wwlwpd** [comment]
Been running a replay test with,

```
postExcludeFiles=( fort.22 fort.15 )
```

And it seems to be working. And I managed to not break emails this time - https://fortytwo.cct.lsu.edu/thredds/catalog/2022/al12/05/ec95d/mike.hpc.lsu.edu/ec95d-replay-supermike-iii/nhcConsensus/catalog.html

**Review by jasonfleming — APPROVED** [review]
This looks good to me. I saw that the `exclude` takes precedence over the `additional`, we should add that to the documentation. :-)

**Comment by wwlwpd** [comment]
Thanks for reminding me of documentation, I will add this to the wiki before I hit the merge button.

**Comment by wwlwpd** [comment]
Updated docs via https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide#opendap

**Pull request merged**
