### PR TITLE
Removed centralized scenario logging

### LINKED ISSUE #1134: zombie `tail -f`observed in docker image when running
image

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #1134

### CODE REVIEW

**Comment by jasonfleming** [comment]
Testing now

**Comment by jasonfleming** [comment]
I think this also resolves #1228 @wwlwpd

**Comment by jasonfleming** [comment]
Might also resolve #732

**Comment by jasonfleming** [comment]
resolves #1005

**Review by wwlwpd — APPROVED** [review]
Looks good to me. I double checked on the availability of Lonestar 5 and Stampede 2, good call on removing them early.

**Pull request merged**
