### PR TITLE
Added checks for ownership and existence

### LINKED ISSUE #874: Reduce chattiness and checking remote permissions in opendap_post2.sh
When posting to most remote servers (not fortytwo), the opendap_post2.sh script must check to see if it is creating directories, and if so, will most likely need to change permissions on those directories so that other Operators can also post there. However, it is often the case that it is not the entire directory hierarchy that can be changed (some directories are not owned by the Operator doing the posting). This causes the attempt to change permissions in those directories to fail and then retry (up to 10 times each time). This results in slow posting and huge log files that are very hard to parse or post.

On remote servers where permissions are an issue, the attempt to change permissions should be limited to cases where it is actually needed and will succeeed.

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #874 

Hoping this is a cleaner change than the issue-874 draft PR

### CODE REVIEW

**Review by wwlwpd — COMMENTED** [review]
Looks good to me. Are you going to add the other files to this PR? If not, may as well make this active and I can approve it.

**Comment by jasonfleming** [comment]
Thank you @wwlwpd I am still testing this ...

**Review by wwlwpd — APPROVED** [review]
looks good to me

**Comment by wwlwpd** [comment]
Squash merged manually with rebase/cherrypick. Closing because it's been merged.

**Pull request closed without merging**
