### PR TITLE
Added script and template to support downloading GFS

### LINKED ISSUE #843: add support for GFS

### PR DESCRIPTION
**Pull request by jasonfleming**
resolves #843

### CODE REVIEW

**Comment by jasonfleming** [comment]
I have this running successfully on my desktop machine; it is ready for full scale testing on one of the HPC machines, so that is my next move.

**Comment by jasonfleming** [comment]
This requires a more modern version of wgrib2 (I am using v3.1.1).

**Comment by jasonfleming** [comment]
I updated the `wgrib2` installation to the latest version and moved the installed location to `$SCRIPTDIR/bin`. This is running as expected on my desktop machine as well as ls6.

**Review by wwlwpd — APPROVED** [review]
required a minor fix to asgs-brew.pl, but looks good overall

**Comment by wwlwpd** [comment]
I am going to be merging this as a manual squash, `issue-843-sq`

**Pull request closed without merging**
