### PR TITLE
Add river template

### PR DESCRIPTION
**Pull request by enikidis**
#1032 
Generated river templates.

### CODE REVIEW

**Comment by jasonfleming** [comment]
Hey @enikidis I've had a brief look at this, and I am wondering: How did you generate the flux values for the Atchafalaya River boundary? I did not see this in the Google Sheet used to compute these b.c.s (but maybe I missed it or did not understand).

Also, I recommend that the fort.15 template file contents have the `Total River Flow` annotation that indicates the intended river flux on each boundary so that it matches the template file name. For example, in the LAERDCv5i 15kcms template file, the lines that indicate the fluxes are as follows:
```
1.995270747  .000000    !...River 1 Node 1 (Total River Flow: 4247.0000 cms, Avg Lat/Long: -91.801121,30.979759)
...
10.97330636  .000000    !...River 2 Node 1 (Total River Flow: 10194.0000 cms, Avg Lat/Long: -91.573385,31.026883)
```
which match the original annotations, even though the flux numbers have been updated to 15kcms. The reason for this recommendation is that the ASGS will rename all these files to a simple `fort.15`, which means that the metadata in the template file name will be lost when the results are copied to fortytwo, leaving the flux numbers (which are difficult for a human to evaluate) in the fort.15 file with annotations that do not match the boundary conditions. It will then be difficult to determine what boundary conditions were actually applied.

**Comment by carolakaiser** [comment]
@jasonfleming Thank you for your review and the comments.
Could you please share the information what gage station is used to identify the discharge of the Atchafalaya River?

**Comment by jasonfleming** [comment]
Discussions are underway to change the ratio to 50/50:

https://www.daily-review.com/news-local/changing-mississippi-flow-down-atchafalaya-could-be-solution-basin-issues

**Review by wwlwpd — COMMENTED** [review]
Provided this gets rebased and squashed (I'll do it) and it's just new files, I'll merge this as soon as I get confirmation from @enikidis .

**Comment by wwlwpd** [comment]
Closing this, added this commit from @enikidis's remote via `cherry-pick`.

**Comment by jasonfleming** [comment]
I have added the little writeup about the Atchafalaya river flux to the ASGS Developers Guide.

**Pull request closed without merging**
