### PR TITLE
Replace unsupported strftime with external `date` call in awk script.

### LINKED ISSUE #661: awk on some platforms do not have the strftime function
I am seeing error messages like the following on some platforms
```
awk: /work/asgs/monitoring/scenarioStatus.awk: line 63: function strftime never defined
```
Not sure what the best solution would be. It might make more sense to replace the offending awk scripts with perl scripts (as opposed to making sure we have access to gawk across all platforms). Please advise.

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 661: Uses external call to `date` with "getline" capture of output
in awk to capture formatted date. Improves portability of script.

Resolves #661.

### CODE REVIEW

**Comment by jasonfleming** [comment]
I have to confess that I do not understand why this fix works, but I can confirm that it does. :-) I have also duplicated this fix in the `timestamp.awk` script, because it was suffering from the same issue. @wwlwpd can you have a look?

**Review by jasonfleming — APPROVED** [review]
It works! Thank you :-)

**Comment by wwlwpd** [comment]
> I have to confess that I do not understand why this fix works, but I can confirm that it does. :-) I have also duplicated this fix in the `timestamp.awk` script, because it was suffering from the same issue. @wwlwpd can you have a look?

```
 "date +%Y-%m-%d-T%H:%M:%S%z" | getline date
```

Is to `awk`, what the following is to the shell:

```
date=$(date +%Y-%m-%d-T%H:%M:%S%z)
```

It's a little confusing because the first `date` in the fix is the call to `date` in a subshell; the second `date` is the variable that gets used in the following line. In `awk`, `getline` is a little more explicit for getting the output of `date +%Y-%m-%d-T%H:%M:%S%z`.

**Comment by wwlwpd** [comment]
Thanks for applying it to the other script.

**Pull request merged**
