### PR TITLE
Fixed bug in 'make' usage for swan/ADCIRC integration.

### LINKED ISSUE #545: building adcprep requires SWAN=enable but padcswan and adcswan do not
When using the `build adcirc` capability of ASGS Shell, the command line it creates adds `SWAN=enable` to the command line when building `adcswan` and `padcswan`, but this parameter is not needed for those targets (I guess the semantics assume that enabling SWAN is implicit for these targets). 

However, the `SWAN=enable` setting is required on the `make` command line when building `adcprep` ... this causes `adcprep` to look for a `fort.26` SWAN input file at run time and to copy it to each subdomain subdirectory if it is found.

### PR DESCRIPTION
**Pull request by wwlwpd**
Issue 545: Updated the 'make' commands to proper use. Basically,
had them resersed (e.g., wrt 'swan=enable').

Resolves #545.

### CODE REVIEW

**Review by jasonfleming — CHANGES_REQUESTED** [review]
Thank you for this. The `SWAN=enable` has to have `SWAN` in all caps. It is only required for building `adcprep` but I don't think it will have any negative effect on the other targets in `ADCIRC_BINS`. 

Not sure if this will be addressed in a separate pull request, but the `NETCDFROOT` setting should also be removed (not used/needed) and the `NETCDF=enable ...` etc should be applied to `ADCSWAN_BINS` targets also.

**Comment by wwlwpd** [comment]
Should I remove all references to `NETCDFROOT`, @jasonfleming?

**Review by jasonfleming — APPROVED** [review]

**Comment by jasonfleming** [comment]
I have tweaked the make command line and I am testing the build now on supermic.

**Comment by jasonfleming** [comment]
Tried to build this on supermic just now, and my terminal froze! Twice!
```
mpif90 -DADCNETCDF -I/work/jgflemin/opt/default/include -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -c -I . -I /work/jgflemin/adcirc-cg-v53release-issue-549-intel/prep -O2 -FI -assume byterecl -132 -xAVX -assume buffered_io -DADCNETCDF -I/work/jgflemin/opt/default/include -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -DREAL8 -DLINUX -DCSCA -DCMPI -I /work/jgflemin/adcirc-cg-v53release-issue-549-intel/work/odir4/ -o /work/jgflemin/adcirc-cg-v53release-issue-549-intel/work/odir4/sizes.o  /work/jgflemin/adcirc-cg-v53release-issue-549-intel/src/sizes.F
if [ "`echo *.mod`" != '*.mod' ]; then mv *.mod /work/jgflemin/adcirc-cg-v53release-issue-549-intel/work/odir4/; fi
^Cmake[1]: *** Deleting file `/work/jgflemin/adcirc-cg-v53release-issue-549-intel/work/odir4/sizes.o'
^C^C^C^C^C
```
Won't unfreeze, even with `Ctrl-c` ... I wonder if they are having issues with the Intel licenses again.

**Comment by wwlwpd** [comment]
@jasonfleming - that's the failure mode I saw when it was happening. Merging, thanks!

**Pull request merged**
